adcbv/adcbv/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from info import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.IndexView.as_view()),
    url(r'^info/', include ('info.urls', namespace='info')),
]

adcbv/info/urls.py
from django.conf.urls import url
from info import views

app_name = 'info'

urlpatterns = [
        url(r'^$', views.SchoolListView.as_view(), name='list'),
        url(r'^(?P<pk>[-\w]+)/$', views.SchoolDetailView.as_view() , name='detal'),
]

adcbv/info/models.py
from django.db import models

# Create your models here.


class School(models.Model):
    name = models.CharField(max_length=70)
    principal = models.CharField(max_length=70)
    location = models.CharField(max_length=70)

    def __str__(self):
        return self.name

class Student(models.Model):
    name = models.CharField(max_length=70)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name='students', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

adcbv/info/views.py
from django.shortcuts import render
from django.views.generic import View, TemplateView, ListView, DetailView
from django.http import HttpResponse
from . import models
# Create your views here.


class IndexView(TemplateView):
    template_name = 'info/index.htm'

class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School

class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School

    template_name = 'info/school.htm'

adcbv/info/templates/info/newbase.htm
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Base</title>
</head>

<body>

    <nav class="navbar navbar-default navbar-static-top">
        <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="{% url 'info:list' %}">School</a></li>
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
            <li><a class="navbar-link" href=""></a></li>
        </ul>
    </nav>
    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>
</body>

</html>

adcbv/info/templates/info/school.htm
{% extends 'info/newbase.htm' %}
{% block body_block %}

<div class="jumbotron">
    <h1>Welcome to school details</h1>
    <h2>School details:</h2>
    <p>Name: {{ school.name }}</p>
    <p>Principal: {{ school_deatil.principal }}</p>
    <p>Location: {{ school_deatil.location }}</p>
    <h3>Students:</h3>

    {% for students in school_detail.students.all %}
    <p>{{ student.Name }} who is {{ student.Age }} years old</p>
    {% endfor %}
</div>

{% endblock %}

adcbv/info/templates/info/school_list.html
{% extends 'info/newbase.htm' %}

{% block body_block %}
<h1>Welcome to list of schools!</h1>
<ol>
    {% for school in schools %}
    <h2>
        <li><a href="{{ school.id }}">{{ school.name }}</a></li>
    </h2>
    {% endfor %}
</ol>
{% endblock %}

adcbv/templates/info/base.htm
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Base</title>
</head>

<body>

    <nav class="navbar navbar-default navbar-static-top">
        <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="{% url 'info:list' %}">School</a></li>
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
            <li><a class="navbar-link" href=""></a></li>
        </ul>
    </nav>
    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>
</body>

</html>

adcbv/templates/info/index.htm
{% extends "info/base.htm" %}
{% block body_block %}
<div class="jumbotron">
    <h1>Homepage</h1>
</div>
{% endblock %}